# Numpy Exercise


In [2]:
import numpy as np

# 1D Array Mixed and 2D Array Mixed

In [6]:
arr_1D=np.array([1,2.2,3,4,5])

print(arr_1D,"\n")

arr_2D=np.array([[1,2.2,3,4,5],[3,2.006,4,5,6]])

print(arr_2D)

[1.  2.2 3.  4.  5. ] 

[[1.    2.2   3.    4.    5.   ]
 [3.    2.006 4.    5.    6.   ]]


# Fixed  Array

In [6]:
import numpy as np
arr_Fixed=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9],int)

print(arr_Fixed,'\n')

arr_Fixed2D=np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],int)

print(arr_Fixed2D)

[0 1 2 3 4 5 6 7 8 9] 

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


# arr.ndim -> Dimentional
# arr.shape -> (rows,column)

# Array Slicing: Accessing Subarrays

In [33]:
arr3=np.arange(10)
print(arr4)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
arr3[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr3[3:8]

array([3, 4, 5, 6, 7])

In [46]:
arr4=np.arange(6).reshape(3,2)
print(arr4)

[[0 1]
 [2 3]
 [4 5]]


In [48]:
arr5=np.arange(30).reshape(2,15)

print(arr5)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [52]:
split=np.hsplit(arr5,3)
split

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [53]:
split2=np.vsplit(arr5,2)
split2

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [40]:
arr6=np.random.randint(5,10, size=(2,3))

print(arr6)

[[8 7 6]
 [7 9 7]]


In [42]:
arr6[:,1:3]

array([[7, 6],
       [9, 7]])

In [57]:
arr7=np.array([[2,3,4,5,4,2],[4,6,7,8,6,7]])

print(arr7)

[[2 3 4 5 4 2]
 [4 6 7 8 6 7]]


In [58]:
flattern=arr7.flatten()
flattern

array([2, 3, 4, 5, 4, 2, 4, 6, 7, 8, 6, 7])

In[16]: x = np.arange(10)

x

Out[16]: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In[17]: x[:5] --->>> first five elements

Out[17]: array([0, 1, 2, 3, 4])

In[18]: x[5:] ---->>> elements after index 5


Out[18]: array([5, 6, 7, 8, 9])

In[19]: x[4:7] ---->>> middle subarray



Out[19]: array([4, 5, 6])

44

In[20]: x[::2] ---->>> every other element

Out[20]: array([0, 2, 4, 6, 8])


In[21]: x[1::2] ---->>>every other element, starting at index 1


Out[21]: array([1, 3, 5, 7, 9])

A potentially confusing case is when the step value is negative. In this case, the
defaults for start and stop are swapped. This becomes a convenient way to reverse
an array:

In[22]: x[::-1]  ---->>>all elements, reversed

Out[22]: array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In[23]: x[5::-2] ----->>>reversed every other from index 5


Out[23]: array([5, 3, 1])


# Reversed Array

In [2]:
import numpy as np
A = np.arange(8).reshape((2,2,2))
A

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [3]:
np.flip(A)

array([[[7, 6],
        [5, 4]],

       [[3, 2],
        [1, 0]]])

A = np.arange(8).reshape((2,2,2))
A
array([[[0, 1],
        [2, 3]],
       [[4, 5],
        [6, 7]]])
        
flip(A, 0)

array([[[4, 5],
        [6, 7]],
       [[0, 1],
        [2, 3]]])
        
flip(A, 1)
array([[[2, 3],
        [0, 1]],
       [[6, 7],
        [4, 5]]])
        
np.flip(A)
array([[[7, 6],
        [5, 4]],
       [[3, 2],
        [1, 0]]])
        
np.flip(A, (0, 2))
array([[[5, 4],
        [7, 6]],
       [[1, 0],
        [3, 2]]])
        
A = np.random.randn(3,4,5)
np.all(flip(A,2) == A[:,:,::-1,...])
True

# Concate Array

a = np.array([[1, 2], [3, 4]])

b = np.array([[5, 6]])

np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

In [9]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [12]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [14]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
[6, 5, 4]])
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [16]:
y= np.array([[99],
[99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

# Slicing Array and Change small pieces will change the main Array

In [3]:
arr8=np.array([[2,3,4,5,4,2],[4,6,7,8,6,7]])
arr8

array([[2, 3, 4, 5, 4, 2],
       [4, 6, 7, 8, 6, 7]])

In [5]:
arr9=arr8[0:2,0:2]

arr9

array([[2, 3],
       [4, 6]])

In [6]:
arr9[0,0]=99

arr9

array([[99,  3],
       [ 4,  6]])

In [7]:
arr8

array([[99,  3,  4,  5,  4,  2],
       [ 4,  6,  7,  8,  6,  7]])

# Sorting in Numpy

In [3]:
import numpy as np
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [4]:
arr10 = np.random.RandomState(42)
X = arr10.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [5]:
# sort each column of X
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [6]:
# sort each row of X
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

# Partial Sorts: Partitioning

In [9]:
import numpy as np

x = np.array([7, 2, 3, 1, 6, 5, 4])
#the first three values in the resulting array are the three smallest in the array

np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [11]:
X1 = arr10.randint(0, 10, (4, 6))
np.partition(X1, 2, axis=1)

array([[0, 1, 2, 6, 3, 7],
       [1, 3, 5, 7, 5, 9],
       [1, 1, 3, 9, 5, 9],
       [3, 4, 6, 8, 7, 7]])

np.sum                np.nansum               Compute sum of elements

np.prod               np.nanprod              Compute product of elements

np.mean               np.nanmean              Compute median of elements

np.std                np.nanstd               Compute standard deviation

np.var                np.nanvar               Compute variance

np.min                np.nanmin               Find minimum valu

np.max                np.nanmax               Find maximum value

np.argmin             np.nanargmin            Find index of minimum value

np.argmax             np.nanargmax            Find index of maximum value

np.median             np.nanmedian            Compute median of elements

np.percentile         np.nanpercentile        Compute rank-based statistics of elements

np.any                N/A Evaluate            whether any elements are true

np.all                N/A Evaluate            whether all elements are true
